---
delegatebot:
  watch:
  - target: { channel: &diego C02FM2BPE }
  delegate: &interrupts
    if:
      when:
        - hours: { tz: America/Los_Angeles, start: 06:00, end: 18:00 }
        - day: { tz: America/Los_Angeles, days: [ Mon, Tue, Wed, Thu, Fri ] }
        - not: { date: { tz: America/Los_Angeles, dates: [ 2019-01-01, 2019-01-21, 2019-02-18, 2019-05-27, 2019-07-04, 2019-09-02, 2019-11-28, 2019-11-29, 2019-12-25 ] } }
      then:
        literalmap:
          from:
            pairist:
              team: diego
              role: Interrupt
              password: $PAIRIST_TEAM_DIEGO
          users:
            Amin: U077YLS56
            Edwin: U092YCSRG
            John: U056ACK7P
            Maria: U043GTWND
            Mark: U05661PTK
            Robert: U0J1NFPUG
            Sunjay: U1QBM6CUD
            Will: U064Q3Z39
  options:
    empty_message: Sorry, no interrupt is available right now. The community may be able to help, or feel free to ping again later.
