---
delegatebot:
  watch:
  - target: { channel: &release-integration C0FAEKGUQ }
  delegate:
    if:
      when:
      - hours: { tz: America/Los_Angeles, start: 09:00, end: 18:00 }
      - day: { tz: America/Los_Angeles, days: [ Mon, Tue, Wed, Thu, Fri ] }
      - not: { date: { tz: America/Los_Angeles, dates: [ 2019-01-01, 2019-01-21, 2019-02-18, 2019-05-27, 2019-07-04, 2019-09-02, 2019-11-28, 2019-11-29, 2019-12-25 ] } }
      then:
        literalmap:
          from:
            pairist:
              team: relint
              role: Community
          users:
            Andrew Chang: UC7CRDSL9
            Andrew Costa: UKGS80CG6
            Dave Walter: U08D6EN73
            Sebastian Vidrio: U6WBMK9QW
            Weyman Fung: U04CEERCS
  options:
    empty_message: Sorry, I wasn't able to automagically find an interrupt for you.
